const {contextBridge, ipcRenderer} = require("electron");

contextBridge.exposeInMainWorld("sceneFlow", {
  projects: () => ipcRenderer.invoke("projects:list"),
  sceneDetail: (project, scene) => ipcRenderer.invoke("scene:detail", project, scene),
  saveSceneDocument: (project, scene, request) => ipcRenderer.invoke("scene:save-document", project, scene, request),
  seedanceSkillPolicy: () => ipcRenderer.invoke("prompt:seedance-skill-policy"),
  syncPromptHandoff: payload => ipcRenderer.invoke("prompt:sync-handoff", payload),
  startCodexPrompt: (project, jobId, skillProvenance) => ipcRenderer.invoke("prompt:start-codex", project, jobId, skillProvenance),
  getPromptJob: (project, jobId) => ipcRenderer.invoke("prompt:get-job", project, jobId),
  cancelPromptJob: (project, jobId) => ipcRenderer.invoke("prompt:cancel-job", project, jobId),
  approvePromptJob: (project, jobId, evidence) => ipcRenderer.invoke("prompt:approve-job", project, jobId, evidence),
  promptHistory: (project, scene) => ipcRenderer.invoke("prompt:history", project, scene),
  createProject: (title, screenplay) => ipcRenderer.invoke("project:create", title, screenplay),
  connectCodexSources: project => ipcRenderer.invoke("project:connect-codex-sources", project),
  deleteProject: project => ipcRenderer.invoke("project:delete", project),
  compileWorkspace: (project, scene) => ipcRenderer.invoke("scene:compile-workspace", project, scene),
  pickImages: (project, scene, role) => ipcRenderer.invoke("asset:pick-images", project, scene, role),
  pickPreviewImages: (project, scene, role) => ipcRenderer.invoke("asset:pick-preview-images", project, scene, role),
  openAssetsFolder: (project, scene, blockId, model, items) => ipcRenderer.invoke("scene:open-assets-folder", project, scene, blockId, model, items),
  openBlockLibrary: (project, scene, block, model) => ipcRenderer.invoke("ai:open-block-library", project, scene, block, model),
  openBlockLibraries: (project, scene, model) => ipcRenderer.invoke("ai:open-block-libraries", project, scene, model),
  saveBlockLibrary: (project, scene, config) => ipcRenderer.invoke("ai:save-block-library", project, scene, config),
  saveUploadPack: (project, scene, config) => ipcRenderer.invoke("ai:save-upload-pack", project, scene, config),
  copyImage: source => ipcRenderer.invoke("image:copy-to-clipboard", source),
  composeBlockStoryboard: (project, scene, block, items) => ipcRenderer.invoke("storyboard:compose-block", project, scene, block, items),
  saveBlockStoryboard: (project, scene, block, dataUrl) => ipcRenderer.invoke("storyboard:save-composite", project, scene, block, dataUrl),
  exportAiPackage: (project, scene, config) => ipcRenderer.invoke("ai:export-package", project, scene, config),
  runProductionAgent: (project, scene, request) => ipcRenderer.invoke("production-agent:run", project, scene, request),
});
